singleQuote: true
semi: true
useTabs: false
tabWidth: 2
printWidth: 120
trailingComma: 'es5'
bracketSpacing: true # Objects
braceSpacing: false # Arrays
spaceBeforeFunctionParen: false
arrowParens: always
endOfLine: lf
