version: '3'
services:
  api-server:
    image: api-server.dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    network_mode: host
